### ISSUE TITLE
A warning is issued after yarn start on v2.0.0

### ISSUE THREAD

**Issue by PawBud** [electron-elements/send-feedback#66]
I noticed that after running send-feedback version 2.0.0 a warning is issued which says 
**(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397**

![Screenshot from 2020-05-16 12-48-35](https://user-images.githubusercontent.com/48093317/82113420-92e90780-9773-11ea-975b-c62d7b2aab90.png)

**Comment by PawBud** [comment]
I will be happy to issue a PR that can fix the warning if there is any.

**Comment by priyank-p** [comment]
I saw that too, I don't think there is something we can do here, especially because we don't need `app.rendererProcessReuse`.

**Comment by priyank-p** [comment]
Closing this now, but let me know if you think we need to take a look here.

**Comment by PawBud** [comment]
No, we don't because as you said we don't really need `app.rendererProcessReuse`.
