### ISSUE TITLE
Close button is not visible on the yarn build and the v2.0.0 release build

### ISSUE THREAD

**Issue by PawBud** [electron-elements/send-feedback#67]
So I ran `git pull upstream master` on my local repo and ran `yarn` to install the new dependencies and then ran `yarn start`. The electron build showed this:-
![Screenshot from 2020-05-16 12-53-03](https://user-images.githubusercontent.com/48093317/82113690-94b3ca80-9775-11ea-8505-5476bb295a54.png)

The send-feedback-v2.0.0 also showed this 
![Screenshot from 2020-05-16 13-03-34](https://user-images.githubusercontent.com/48093317/82113712-b90fa700-9775-11ea-9ae0-9ef8e4442980.png)

I will be happy to help you if you can guide me to where the potential bug is!

If I am doing something wrong then I am sorry; you may close this issue if that's the case :)

**Comment by priyank-p** [comment]
It's behind a flag, so if you do `sendFeedback.showCancelButton = "show"` it should show a cancel button.

**Comment by PawBud** [comment]
ohh understood, So basically this allows users of feedback form to either have the button or not.

**Comment by priyank-p** [comment]
Yes, if the app thinks that they need to use the cancel button we allow them to show it, and tell them when a user clicks on it. We don't show it by default because we don't do anything when the button is clicked.

**Comment by priyank-p** [comment]
I thought about clear everything a user may have typed in when this button was clicked but I am don't think that the right design here.
